package com.trader.core;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;
import java.util.List;

/**
 * Represents a trading signal generated by the strategy.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TradingSignal {
    private String symbol;
    private SignalType type;
    private SignalAction action;
    private double price;
    private double confidence;
    private Instant timestamp;
    private List<String> triggeredRules;
    private double suggestedStopLoss;
    private double suggestedTakeProfit;
    private double suggestedQuantity;
    private SignalStrength strength;

    public enum SignalType {
        BULLISH,        // Bullish signal detected
        BEARISH,        // Bearish signal detected
        ENTRY_LONG,     // Entry long signal (for order execution)
        ENTRY_SHORT,    // Entry short signal (for order execution)
        EXIT_LONG,      // Exit long signal (for order execution)
        EXIT_SHORT,     // Exit short signal (for order execution)
        NEUTRAL         // No clear signal
    }

    public enum SignalAction {
        BUY,
        SELL,
        HOLD,
        CLOSE
    }

    public enum SignalStrength {
        WEAK(0.3),
        MODERATE(0.5),
        STRONG(0.7),
        VERY_STRONG(0.9);

        private final double minConfidence;

        SignalStrength(double minConfidence) {
            this.minConfidence = minConfidence;
        }

        public double getMinConfidence() {
            return minConfidence;
        }

        public static SignalStrength fromConfidence(double confidence) {
            if (confidence >= VERY_STRONG.minConfidence) return VERY_STRONG;
            if (confidence >= STRONG.minConfidence) return STRONG;
            if (confidence >= MODERATE.minConfidence) return MODERATE;
            return WEAK;
        }
    }

    /**
     * Returns true if this is a detection signal (bullish or bearish).
     */
    public boolean isDetectionSignal() {
        return type == SignalType.BULLISH || type == SignalType.BEARISH;
    }

    /**
     * Returns true if this is a bullish signal.
     */
    public boolean isBullish() {
        return type == SignalType.BULLISH || type == SignalType.ENTRY_LONG;
    }

    /**
     * Returns true if this is a bearish signal.
     */
    public boolean isBearish() {
        return type == SignalType.BEARISH || type == SignalType.ENTRY_SHORT ||
               type == SignalType.EXIT_LONG;
    }

    /**
     * Returns true if this is an entry signal.
     */
    public boolean isEntrySignal() {
        return type == SignalType.ENTRY_LONG || type == SignalType.ENTRY_SHORT;
    }

    /**
     * Returns true if this is an exit signal.
     */
    public boolean isExitSignal() {
        return type == SignalType.EXIT_LONG || type == SignalType.EXIT_SHORT;
    }

    /**
     * Returns true if the signal confidence is above the threshold.
     */
    public boolean isConfident(double threshold) {
        return confidence >= threshold;
    }

    /**
     * Formats the signal for display or notification.
     */
    public String format() {
        StringBuilder sb = new StringBuilder();
        sb.append(String.format("SIGNAL DETECTED%n"));
        sb.append(String.format("Pair: %s%n", symbol));
        sb.append(String.format("Type: %s%n", type));
        sb.append(String.format("Action: %s%n", action));
        sb.append(String.format("Price: %.2f%n", price));
        sb.append(String.format("Confidence: %.1f%%%n", confidence * 100));
        sb.append(String.format("Strength: %s%n", strength));

        if (triggeredRules != null && !triggeredRules.isEmpty()) {
            sb.append(String.format("Triggered Rules:%n"));
            for (String rule : triggeredRules) {
                sb.append(String.format("  - %s%n", rule));
            }
        }

        if (suggestedStopLoss > 0) {
            sb.append(String.format("Suggested Stop Loss: %.2f%n", suggestedStopLoss));
        }
        if (suggestedTakeProfit > 0) {
            sb.append(String.format("Suggested Take Profit: %.2f%n", suggestedTakeProfit));
        }

        return sb.toString();
    }
}
